### ISSUE TITLE
About text font-size too small

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#10]
Could be more bold and visible. Now not readable. 

## Question

What kind of typography rules do you use? Have you thought about implementing something like [typography.js](https://kyleamathews.github.io/typography.js/)? It's a quick fix if you want to focus more on development instead of design.

**Comment by RubenNijhuis** [comment]
Will look into it, seems like something that could help the whole site. Thanks!

**Comment by RubenNijhuis** [comment]
Updated is readable on all stuffs!
