### ISSUE TITLE
About text too negative

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#11]
Very subjective this 'issue' and maybe more an enhancement. But I feel like your writing about yourself can be upgraded to a more positive level. Or you like this vibe?

**Comment by RubenNijhuis** [comment]
Mmmm don't really know, I always feel a bit pretentious when writing about myself. Will try to see what I can change :)

**Comment by RubenNijhuis** [comment]
Updated I hope this is better?

**Comment by danoszz** [comment]
@RubenNijhuis Yes much better! Only it consists of some grammar and style mistakes. 

* Use only one writing perspective 'He' or 'I'. Good read [here](https://nl.wikihow.com/In-de-derde-persoon-schrijven) in Dutch. 

**Old**
A young developer who loves working with new and interesting projects. Been developing since 2018 and hasn't stopped since. I believe that the true hart of a project stems from the people that use it, that's also where I lay my focus. I love working with people who dare to bring something new to the table. Bringing ideas to the big screen is what I do, and having fun doing it is my favorite part.

**Suggested**
A young developer who loves working with new and interesting projects. Started developing in 2018 and never stopped since. The true heart of a project stems from the people that use it, that's also where I put my focus. Love to work with people who dare to bring something new to the table. Bringing ideas to the big screen is what I do. Having fun doing it is my favourite part.

Good job on this one ✨

**Comment by RubenNijhuis** [comment]
Added it thanks!
