### ISSUE TITLE
Menu icon not showing

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#13]
The menu toggle icon is now a '?' instead of an icon.

<img width="299" alt="Screen Shot 2019-03-25 at 19 20 46" src="https://user-images.githubusercontent.com/14123926/54940295-24276a00-4f33-11e9-85e7-96d26e68d662.png">

**Comment by RubenNijhuis** [comment]
What do you mean, what kind of icon should be there. I originally added the '?' as a sort of read more page.

**Comment by RubenNijhuis** [comment]
I am going to leave this as is. I might change it later but I don't find it important enough to change to an icon.

**Comment by danoszz** [comment]
@RubenNijhuis I advise replacing the '?' icon with a text 'about' at least. It reminds users of the unknown character replacement: `U+FFFD � REPLACEMENT CHARACTER used to replace an unknown, unrecognized or unrepresentable character`
