### ISSUE TITLE
Idea: color generator for color scheme

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#14]
Would be fun to have a color scheme generated on each time when page is reloaded.

**Comment by RubenNijhuis** [comment]
Sounds very fun, will add it as a feature!

**Comment by RubenNijhuis** [comment]
Added it! 5 different color schemes are now present.

**Comment by danoszz** [comment]
@RubenNijhuis Looks good, how did you do it, and in which push can I view it? Remember to update the repo synchronously with the server.

**Comment by RubenNijhuis** [comment]
I will add it to the repo in the next push.
