### ISSUE TITLE
About section not visible

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#3]
## Current status

Where can I find information about you? Next to seeing projects a client or visitor is also interested in the person behind the website.

## Nice to have

Create a modal containing your 'about' information. Show a picture, add some text and throw some links.

**Comment by RubenNijhuis** [comment]
After I finished the other todo's I will work on this, currently not the highest priority.

**Comment by RubenNijhuis** [comment]
Finished!
