### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#4]
## Current status

When viewed on mobile, website is not usable.

<img width="586" alt="Screen Shot 2019-03-18 at 21 13 14" src="https://user-images.githubusercontent.com/14123926/54556961-c17a1f80-49c2-11e9-9fa3-aa853aee4d23.png">

## Nice to have

A responsive view through your projects, maybe make a simple column instead of a row?

**Comment by RubenNijhuis** [comment]
Added it to the styling! Column is being used.
