### ISSUE TITLE
Create README.md

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#5]
## Current status

The project has no `README.md` file.

## Nice to have

* Although not essential for a successful project, it is smart to incorporate a basic `README.md` file into your workflow. 
* Just a quick guide to set up a local web server or whatsoever. When excluding `node_modules` as referenced in #1 an install guide too.

**Comment by RubenNijhuis** [comment]
Will be adding it on the next push, will include whole setup + how to contribute.
