### ISSUE TITLE
Console shows log items

### ISSUE THREAD

**Issue by danoszz** [RubenNijhuis/portfolio_site#6]
## Current status

Console shows logged project item numbers.

<img width="832" alt="Screen Shot 2019-03-18 at 21 17 10" src="https://user-images.githubusercontent.com/14123926/54557255-5f6dea00-49c3-11e9-9157-435d6757ba32.png">

## Nice to have

* Although it's for local use, keep in my that when ready for production and/or publishing a console should not contain any unnecessary logs.

**Comment by RubenNijhuis** [comment]
For development it was needed, but I am already planning on adding webpack.
